### ISSUE TITLE
Pen drive is not working

### ISSUE THREAD

**Issue by Luciogi** [crdroidandroid/android_device_xiaomi_chime#4]
Hi!
I am using crdroid rom on redmi 9t. I can't use my USB pendrive on mobile via otg.
USB is formated with FAT32. Although I tried usb keyboard which was working
Logs after connecting pendrive t
[2021-12-08-20-01-56.txt](https://github.com/crdroidandroid/android_device_xiaomi_juice/files/7676907/2021-12-08-20-01-56.txt)

[2021-12-08-20-00-52.txt](https://github.com/crdroidandroid/android_device_xiaomi_juice/files/7676905/2021-12-08-20-00-52.txt)
.

![Screenshot_20211208-200000653](https://user-images.githubusercontent.com/84625092/145231496-39f5a6bf-c393-40cb-ae9b-9a6a3cf4adef.jpg)
![Screenshot_20211208-200017427](https://user-images.githubusercontent.com/84625092/145231506-c420aa36-6b1e-4b80-ac59-48a366c0c1d6.jpg)

**Comment by GtrCraft** [comment]
Reformat drive from within android or recovery. Works fine here.

**Comment by Luciogi** [comment]
@GtrCraft thanks for confirmation.
I just flashed miui weekly rom , then flashed again crdroid now usb is working.
I also realized that , i was not pushing USB pendrive into otg, so this is my mistake
