### ISSUE TITLE
Reorient feature has bug on redmi 9t

### ISSUE THREAD

**Issue by Luciogi** [crdroidandroid/android_device_xiaomi_chime#6]
**Device:** Redm 9t
**Rom:** Crdroid 8.6 Vanilla build
**Steps to produce:**
1. Goto Setttings > crDroid Settings > Buttons 
2. Toggle ON Reorient
3. Rotate device in Landscape mode such that power button should be at top
![Screenshot_20220629_155118](https://user-images.githubusercontent.com/84625092/176419949-81e028dd-93c8-49e7-af34-dd61e963775d.png)
5. Then Press Volume down key, you will notice , volume will increase.
**Expected Result:** Volume should decrease.

**Comment by GtrCraft** [comment]
Disable reorient volume buttons and your problem is fixed
